import { StyleSheet, Dimensions } from 'react-native';

const { width } = Dimensions.get('window');

export const styles = StyleSheet.create({
  outerSafeArea: {
    flex: 1,
    backgroundColor: '#FAFDF9',
  },
  screenContainer: {
    flex: 1,
    backgroundColor: '#FAFDF9',
    alignItems: 'center',
    width: '100%',
  },
  mobileCanvas: {
    width: '100%',
    maxWidth: 480,
    flex: 1,
    backgroundColor: '#FAFDF9',
    position: 'relative',
  },
  scrollContent: {
    paddingBottom: 76,
  },

  /* TOP HEADER STYLES */
  topHeaderBar: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 10,
  },
  locationSelector: {
    flexDirection: 'column',
    justifyContent: 'center',
  },
  locationTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  deliveringToText: {
    fontSize: 13,
    fontWeight: '700',
    color: '#123C24',
    marginLeft: 6,
    marginRight: 2,
  },
  locationAddressText: {
    fontSize: 11.5,
    fontWeight: '400',
    color: '#64748B',
    marginTop: 2,
    marginLeft: 22,
  },
  rightActionRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  iconButton: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: '#FFFFFF',
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.06,
    shadowRadius: 3,
    elevation: 2,
    position: 'relative',
    borderWidth: 1,
    borderColor: '#F1F5F9',
  },
  notificationBadge: {
    position: 'absolute',
    top: 7,
    right: 7,
    width: 7,
    height: 7,
    borderRadius: 3.5,
    backgroundColor: '#EF4444',
  },
  cartBadge: {
    position: 'absolute',
    top: 2,
    right: 2,
    width: 17,
    height: 17,
    borderRadius: 8.5,
    backgroundColor: '#16A34A',
    justifyContent: 'center',
    alignItems: 'center',
  },
  cartBadgeText: {
    fontSize: 10,
    fontWeight: '700',
    color: '#FFFFFF',
  },

  /* SEARCH BAR STYLES */
  searchSection: {
    paddingHorizontal: 16,
    marginTop: 4,
    marginBottom: 14,
  },
  searchBarCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    height: 46,
    paddingHorizontal: 14,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1.5 },
    shadowOpacity: 0.04,
    shadowRadius: 5,
    elevation: 2,
  },
  searchInput: {
    flex: 1,
    marginLeft: 10,
    marginRight: 8,
    fontSize: 12.5,
    color: '#1E293B',
    paddingVertical: 0,
    outlineStyle: 'none',
  },

  /* TITLE SECTION STYLES */
  titleSection: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 16,
    marginBottom: 14,
  },
  titleLeftCol: {
    flex: 1,
    paddingRight: 6,
  },
  mainHeadingText: {
    fontSize: 22,
    fontWeight: '800',
    color: '#0F172A',
    letterSpacing: -0.4,
  },
  subtitleText: {
    fontSize: 11,
    fontWeight: '400',
    color: '#64748B',
    marginTop: 2,
  },
  goodFoodPill: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#EAF7EE',
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: '#C8E6C9',
    flexShrink: 0,
  },
  pillTextCol: {
    marginLeft: 6,
  },
  pillTopText: {
    fontSize: 9,
    fontWeight: '700',
    color: '#15803D',
    lineHeight: 11.5,
  },
  pillBottomTextRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  pillBottomText: {
    fontSize: 8,
    fontWeight: '600',
    color: '#166534',
    lineHeight: 10.5,
  },

  /* CATEGORY LIST CONTAINER */
  listContainer: {
    paddingHorizontal: 16,
    gap: 10,
  },
  categoryRowCard: {
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: 14,
    borderWidth: 1,
    paddingLeft: 4,
    paddingRight: 14,
    paddingVertical: 4,
    height: 72,
    position: 'relative',
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.03,
    shadowRadius: 3,
    elevation: 1,
  },
  rowImageContainer: {
    width: 92,
    height: 64,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 8,
    overflow: 'hidden',
  },
  rowProductImage: {
    width: '100%',
    height: '100%',
    transform: [{ scale: 1.15 }],
  },
  rowTextCol: {
    flex: 1,
    justifyContent: 'center',
    paddingRight: 6,
  },
  rowCategoryTitle: {
    fontSize: 12,
    fontWeight: '700',
    color: '#0F172A',
    lineHeight: 14.5,
  },
  rowItemCountText: {
    fontSize: 8.5,
    fontWeight: '500',
    color: '#64748B',
    marginTop: 1.5,
  },
  rowDescriptionText: {
    fontSize: 8,
    fontWeight: '400',
    color: '#64748B',
    marginTop: 1.5,
    lineHeight: 11,
  },
  rowArrowContainer: {
    width: 20,
    height: 20,
    justifyContent: 'center',
    alignItems: 'center',
  },

  /* NO SEARCH RESULTS */
  noResultsContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 40,
    paddingHorizontal: 16,
  },
  noResultsText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#64748B',
    marginTop: 8,
  },

  /* FIXED BOTTOM NAVIGATION BAR */
  fixedBottomNav: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    height: 56,
    backgroundColor: '#FFFFFF',
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
    borderTopWidth: 1,
    borderTopColor: '#F1F5F9',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -2 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 8,
    zIndex: 100,
  },
  navTabItem: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 4,
  },
  navTabActiveLabel: {
    fontSize: 10.5,
    fontWeight: '700',
    color: '#16A34A',
    marginTop: 2,
  },
  navTabLabel: {
    fontSize: 10.5,
    fontWeight: '500',
    color: '#64748B',
    marginTop: 2,
  },
  navIconContainer: {
    position: 'relative',
  },
  offersRedBadge: {
    position: 'absolute',
    top: -2,
    right: -3,
    width: 7,
    height: 7,
    borderRadius: 3.5,
    backgroundColor: '#EF4444',
    borderWidth: 1,
    borderColor: '#FFFFFF',
  },
});
