import { StyleSheet, Dimensions, Platform } from 'react-native';

const { width: SCREEN_WIDTH } = Dimensions.get('window');

export const styles = StyleSheet.create({
  outerSafeArea: {
    flex: 1,
    backgroundColor: '#FAFDF9',
  },
  screenContainer: {
    flex: 1,
    backgroundColor: '#EEF2F6',
    alignItems: 'center',
  },
  mobileCanvas: {
    width: '100%',
    maxWidth: 480,
    flex: 1,
    backgroundColor: '#FAFDF9',
    position: 'relative',
  },
  scrollContent: {
    paddingBottom: 95,
  },

  // A. TOP HEADER BAR
  topHeaderBar: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 14,
    paddingTop: Platform.OS === 'android' ? 12 : 8,
    paddingBottom: 6,
  },
  locationSelector: {
    flex: 1,
  },
  locationTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  deliveringToText: {
    fontSize: 11,
    fontWeight: '600',
    color: '#64748B',
  },
  locationAddressText: {
    fontSize: 11.5,
    fontWeight: '700',
    color: '#0F2E1E',
    marginTop: 1,
  },
  rightActionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  iconButton: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
  },
  notificationDot: {
    position: 'absolute',
    top: 7,
    right: 8,
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: '#EF4444',
  },
  cartBadge: {
    position: 'absolute',
    top: -3,
    right: -3,
    backgroundColor: '#16A34A',
    borderRadius: 9,
    minWidth: 16,
    height: 16,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 3,
    borderWidth: 1.5,
    borderColor: '#FFFFFF',
  },
  cartBadgeText: {
    color: '#FFFFFF',
    fontSize: 9,
    fontWeight: '700',
  },

  // B. SEARCH BAR
  searchBarContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    marginHorizontal: 12,
    marginTop: 4,
    marginBottom: 8,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    paddingHorizontal: 10,
    height: 38,
    gap: 8,
  },
  searchInput: {
    flex: 1,
    fontSize: 11.5,
    color: '#0F2E1E',
    paddingVertical: 0,
  },
  qrButton: {
    padding: 2,
  },

  // C. CART TITLE & CLEAR CART ROW
  cartHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 14,
    marginTop: 4,
    marginBottom: 10,
  },
  cartTitleCol: {},
  cartMainHeading: {
    fontSize: 20,
    fontWeight: '800',
    color: '#0F2E1E',
    letterSpacing: -0.2,
  },
  cartItemCountSub: {
    fontSize: 11,
    fontWeight: '500',
    color: '#64748B',
    marginTop: 2,
  },
  clearCartBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 8,
    paddingHorizontal: 9,
    paddingVertical: 5,
  },
  clearCartText: {
    fontSize: 10.5,
    fontWeight: '600',
    color: '#475569',
  },

  // D. FREE DELIVERY PROGRESS CARD
  freeDeliveryCard: {
    backgroundColor: '#EAF7EE',
    borderWidth: 1,
    borderColor: '#C6EBD0',
    borderRadius: 12,
    marginHorizontal: 12,
    marginBottom: 12,
    padding: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  freeDeliveryLeft: {
    flex: 1,
    paddingRight: 10,
  },
  freeDeliveryMsgRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginBottom: 6,
  },
  freeDeliveryMsgText: {
    fontSize: 10.5,
    fontWeight: '700',
    color: '#0F2E1E',
  },
  progressBarTrack: {
    height: 5,
    backgroundColor: '#D1EAD7',
    borderRadius: 3,
    overflow: 'hidden',
    width: '100%',
  },
  progressBarFill: {
    height: '100%',
    backgroundColor: '#16A34A',
    borderRadius: 3,
  },
  progressAmtText: {
    fontSize: 9.5,
    fontWeight: '600',
    color: '#64748B',
    marginTop: 4,
  },
  freeDeliveryRight: {
    alignItems: 'center',
    justifyContent: 'center',
    minWidth: 56,
  },
  deliveryVanImg: {
    width: 44,
    height: 26,
    resizeMode: 'contain',
  },
  freeDeliveryBadgeText: {
    fontSize: 8.5,
    fontWeight: '800',
    color: '#16A34A',
    textAlign: 'center',
    marginTop: 2,
    lineHeight: 10,
  },

  // E. CART ITEMS LIST
  cartItemsContainer: {
    paddingHorizontal: 12,
    gap: 8,
    marginBottom: 12,
  },
  cartItemCard: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#EAEFEA',
    borderRadius: 12,
    padding: 10,
    flexDirection: 'row',
    alignItems: 'center',
    position: 'relative',
  },
  itemImgWrapper: {
    width: 56,
    height: 56,
    backgroundColor: '#FFFFFF',
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 2,
  },
  itemImg: {
    width: '100%',
    height: '100%',
    resizeMode: 'contain',
    ...(Platform.OS === 'web'
      ? {
          objectFit: 'contain',
          objectPosition: 'center',
        }
      : {}),
  },
  itemDetails: {
    flex: 1,
    paddingLeft: 10,
    justifyContent: 'center',
  },
  itemNameRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
  },
  itemName: {
    fontSize: 12.5,
    fontWeight: '700',
    color: '#0F2E1E',
  },
  deleteBtn: {
    padding: 4,
    marginTop: -2,
    marginRight: -2,
  },
  itemUnit: {
    fontSize: 10,
    color: '#64748B',
    marginTop: 1,
  },
  itemPriceRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    marginTop: 4,
  },
  itemCurrentPrice: {
    fontSize: 12.5,
    fontWeight: '800',
    color: '#0F2E1E',
  },
  itemOldPrice: {
    fontSize: 10.5,
    color: '#94A3B8',
    textDecorationLine: 'line-through',
  },
  itemDiscountPill: {
    backgroundColor: '#16A34A',
    borderRadius: 4,
    paddingHorizontal: 5,
    paddingVertical: 1.5,
  },
  itemDiscountText: {
    fontSize: 8.5,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  stepperContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#EAF7EE',
    borderRadius: 14,
    paddingHorizontal: 4,
    paddingVertical: 2,
    gap: 4,
    marginLeft: 8,
  },
  stepperBtnMinus: {
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#C6EBD0',
  },
  stepperBtnPlus: {
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: '#16A34A',
    alignItems: 'center',
    justifyContent: 'center',
  },
  stepperCountText: {
    fontSize: 11.5,
    fontWeight: '700',
    color: '#0F2E1E',
    minWidth: 14,
    textAlign: 'center',
  },

  // F. YOU MIGHT ALSO NEED
  crossSellSection: {
    marginHorizontal: 12,
    marginBottom: 14,
  },
  crossSellHeader: {
    backgroundColor: '#EAF7EE',
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
    borderWidth: 1,
    borderColor: '#C6EBD0',
    borderBottomWidth: 0,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 10,
    paddingVertical: 7,
  },
  crossSellHeaderLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  crossSellTitle: {
    fontSize: 11,
    fontWeight: '800',
    color: '#0F2E1E',
  },
  crossSellSub: {
    fontSize: 9,
    color: '#475569',
    marginTop: 1,
  },
  crossSellGrid: {
    backgroundColor: '#FFFFFF',
    borderBottomLeftRadius: 10,
    borderBottomRightRadius: 10,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    padding: 8,
    flexDirection: 'row',
    gap: 6,
    justifyContent: 'space-between',
  },
  crossSellCard: {
    flex: 1,
    backgroundColor: '#FFFFFF',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#EAEFEA',
    padding: 5,
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  crossSellImgWrap: {
    width: '100%',
    height: 52,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 4,
  },
  crossSellProductImg: {
    width: 48,
    height: 48,
    resizeMode: 'contain',
    ...(Platform.OS === 'web'
      ? {
          objectFit: 'contain',
          objectPosition: 'center',
        }
      : {}),
  },
  crossSellName: {
    fontSize: 9,
    fontWeight: '700',
    color: '#0F2E1E',
    width: '100%',
    textAlign: 'left',
  },
  crossSellUnit: {
    fontSize: 7.5,
    color: '#64748B',
    width: '100%',
    textAlign: 'left',
    marginTop: 0.5,
  },
  crossSellBottomRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: '100%',
    marginTop: 3,
  },
  crossSellPrice: {
    fontSize: 10,
    fontWeight: '800',
    color: '#0F2E1E',
  },
  crossSellAddBtn: {
    width: 17,
    height: 17,
    borderRadius: 4,
    backgroundColor: '#16A34A',
    alignItems: 'center',
    justifyContent: 'center',
  },

  // G. BILL DETAILS
  billSection: {
    marginHorizontal: 12,
    marginBottom: 12,
  },
  billHeading: {
    fontSize: 13,
    fontWeight: '800',
    color: '#0F2E1E',
    marginBottom: 8,
  },
  billCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    padding: 10,
  },
  billRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 6,
  },
  billLabel: {
    fontSize: 11,
    color: '#475569',
    fontWeight: '500',
  },
  billValue: {
    fontSize: 11,
    color: '#0F2E1E',
    fontWeight: '700',
  },
  billDiscountValue: {
    fontSize: 11,
    color: '#16A34A',
    fontWeight: '700',
  },
  deliveryChargeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  deliveryOldVal: {
    fontSize: 10.5,
    color: '#94A3B8',
    textDecorationLine: 'line-through',
  },
  deliveryFreeVal: {
    fontSize: 11,
    color: '#16A34A',
    fontWeight: '800',
  },
  billDivider: {
    height: 1,
    backgroundColor: '#E2E8F0',
    marginVertical: 6,
  },
  totalRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 2,
  },
  totalLabel: {
    fontSize: 13,
    fontWeight: '800',
    color: '#0F2E1E',
  },
  totalValue: {
    fontSize: 17,
    fontWeight: '900',
    color: '#0F2E1E',
  },
  savingsBanner: {
    backgroundColor: '#EAF7EE',
    borderWidth: 1,
    borderColor: '#C6EBD0',
    borderRadius: 8,
    paddingVertical: 7,
    paddingHorizontal: 10,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginTop: 8,
  },
  savingsBannerText: {
    fontSize: 10.5,
    fontWeight: '700',
    color: '#16A34A',
  },

  // H. BOTTOM ACTION BUTTONS
  ctaRow: {
    flexDirection: 'row',
    paddingHorizontal: 12,
    marginBottom: 10,
    gap: 8,
  },
  continueBtn: {
    flex: 1,
    backgroundColor: '#F1F5F9',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 8,
    paddingVertical: 11,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
  },
  continueBtnText: {
    fontSize: 11,
    fontWeight: '700',
    color: '#334155',
  },
  checkoutBtn: {
    flex: 1.3,
    backgroundColor: '#16A34A',
    borderRadius: 8,
    paddingVertical: 11,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
  },
  checkoutBtnText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#FFFFFF',
  },

  // I. EMPTY CART VIEW
  emptyCartBox: {
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#EAEFEA',
    padding: 24,
    alignItems: 'center',
    justifyContent: 'center',
    marginHorizontal: 12,
    marginBottom: 14,
  },
  emptyCartText: {
    fontSize: 14,
    fontWeight: '700',
    color: '#0F2E1E',
    marginTop: 8,
  },
  emptyCartSubText: {
    fontSize: 11,
    color: '#64748B',
    marginTop: 2,
    marginBottom: 12,
  },
  shopNowBtn: {
    backgroundColor: '#16A34A',
    borderRadius: 8,
    paddingHorizontal: 16,
    paddingVertical: 8,
  },
  shopNowBtnText: {
    color: '#FFFFFF',
    fontSize: 11.5,
    fontWeight: '700',
  },

  // J. FIXED BOTTOM NAVIGATION
  bottomNavContainer: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: '#FFFFFF',
    borderTopWidth: 1,
    borderTopColor: '#E2E8F0',
    alignItems: 'center',
    zIndex: 100,
  },
  bottomNavCanvas: {
    width: '100%',
    maxWidth: 480,
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
    paddingTop: 6,
    paddingBottom: Platform.OS === 'ios' ? 18 : 8,
  },
  navTab: {
    alignItems: 'center',
    justifyContent: 'center',
    flex: 1,
    position: 'relative',
  },
  navLabel: {
    fontSize: 9.5,
    fontWeight: '500',
    color: '#64748B',
    marginTop: 2,
  },
  navLabelActive: {
    color: '#16A34A',
    fontWeight: '700',
  },
  offerBadge: {
    position: 'absolute',
    top: -2,
    right: 24,
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: '#EF4444',
  },
});
