import { StyleSheet, Dimensions } from 'react-native';

const { width } = Dimensions.get('window');

export const styles = StyleSheet.create({
  outerSafeArea: {
    flex: 1,
    backgroundColor: '#FAFDF9',
  },
  screenContainer: {
    flex: 1,
    backgroundColor: '#FAFDF9',
    alignItems: 'center',
    width: '100%',
  },
  mobileCanvas: {
    width: '100%',
    maxWidth: 480,
    flex: 1,
    backgroundColor: '#FAFDF9',
    position: 'relative',
  },
  scrollContent: {
    paddingBottom: 76,
  },

  /* TOP HEADER STYLES */
  topHeaderBar: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 10,
  },
  locationSelector: {
    flexDirection: 'column',
    justifyContent: 'center',
  },
  locationTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  deliveringToText: {
    fontSize: 13,
    fontWeight: '700',
    color: '#123C24',
    marginLeft: 6,
    marginRight: 2,
  },
  locationAddressText: {
    fontSize: 11.5,
    fontWeight: '400',
    color: '#64748B',
    marginTop: 2,
    marginLeft: 22,
  },
  rightActionRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  iconButton: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: '#FFFFFF',
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.06,
    shadowRadius: 3,
    elevation: 2,
    position: 'relative',
    borderWidth: 1,
    borderColor: '#F1F5F9',
  },
  notificationBadge: {
    position: 'absolute',
    top: 7,
    right: 7,
    width: 7,
    height: 7,
    borderRadius: 3.5,
    backgroundColor: '#EF4444',
  },
  cartBadge: {
    position: 'absolute',
    top: 2,
    right: 2,
    width: 17,
    height: 17,
    borderRadius: 8.5,
    backgroundColor: '#16A34A',
    justifyContent: 'center',
    alignItems: 'center',
  },
  cartBadgeText: {
    fontSize: 10,
    fontWeight: '700',
    color: '#FFFFFF',
  },

  /* SEARCH BAR STYLES */
  searchSection: {
    paddingHorizontal: 16,
    marginTop: 4,
    marginBottom: 16,
  },
  searchBarCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    height: 46,
    paddingHorizontal: 14,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1.5 },
    shadowOpacity: 0.04,
    shadowRadius: 5,
    elevation: 2,
  },
  searchInput: {
    flex: 1,
    marginLeft: 10,
    marginRight: 8,
    fontSize: 12.5,
    color: '#1E293B',
    paddingVertical: 0,
    outlineStyle: 'none',
  },

  /* TITLE SECTION STYLES */
  titleSection: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 16,
    marginBottom: 14,
  },
  titleLeftCol: {
    flex: 1,
    paddingRight: 6,
  },
  mainHeadingText: {
    fontSize: 18,
    fontWeight: '700',
    color: '#0F172A',
    letterSpacing: -0.3,
  },
  subtitleText: {
    fontSize: 10.5,
    fontWeight: '400',
    color: '#64748B',
    marginTop: 2,
  },
  freshChoicesPill: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#EAF7EE',
    paddingHorizontal: 8,
    paddingVertical: 4.5,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: '#C8E6C9',
    flexShrink: 0,
  },
  pillTextCol: {
    marginLeft: 5,
  },
  pillTopText: {
    fontSize: 8,
    fontWeight: '700',
    color: '#15803D',
    lineHeight: 10.5,
  },
  pillBottomText: {
    fontSize: 7,
    fontWeight: '600',
    color: '#166534',
    lineHeight: 9.5,
  },

  /* MAIN 3-COLUMN CATEGORY GRID */
  gridContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    rowGap: 10,
  },
  categoryCard: {
    width: '31.3%',
    borderRadius: 16,
    padding: 7,
    paddingBottom: 8,
    position: 'relative',
    borderWidth: 1,
    justifyContent: 'space-between',
    height: 126,
  },
  cardImageContainer: {
    width: '100%',
    height: 78,
    justifyContent: 'center',
    alignItems: 'center',
    overflow: 'hidden',
  },
  cardProductImage: {
    width: '100%',
    height: '100%',
    transform: [{ scale: 1.14 }],
  },
  allCategoryIconContainer: {
    width: '100%',
    height: 78,
    justifyContent: 'center',
    alignItems: 'center',
  },
  cardBottomRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-end',
    marginTop: 'auto',
  },
  cardTextCol: {
    flex: 1,
    paddingRight: 2,
  },
  cardCategoryTitle: {
    fontSize: 9.5,
    fontWeight: '700',
    color: '#1E293B',
    lineHeight: 12,
  },
  cardItemCountText: {
    fontSize: 7.5,
    fontWeight: '500',
    color: '#64748B',
    marginTop: 2,
  },
  cardArrowCircle: {
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: '#FFFFFF',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.08,
    shadowRadius: 2,
    elevation: 2,
    marginLeft: 2,
  },

  /* FEATURED CATEGORIES SECTION */
  featuredSectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 16,
    marginTop: 20,
    marginBottom: 10,
  },
  featuredHeadingText: {
    fontSize: 16,
    fontWeight: '800',
    color: '#0F172A',
    letterSpacing: -0.2,
  },
  seeAllButton: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 4,
    paddingHorizontal: 2,
  },
  seeAllText: {
    fontSize: 12.5,
    fontWeight: '600',
    color: '#16A34A',
  },
  featuredRowContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    width: '100%',
    gap: 6,
  },
  featuredCard: {
    flex: 1,
    minWidth: 0,
    flexShrink: 1,
    borderRadius: 13,
    paddingTop: 6,
    paddingBottom: 0,
    paddingHorizontal: 0,
    borderWidth: 1,
    position: 'relative',
    height: 96,
    justifyContent: 'space-between',
    overflow: 'hidden',
  },
  featuredCardTopRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    width: '100%',
    paddingHorizontal: 6,
  },
  featuredCardTextCol: {
    flex: 1,
    minWidth: 0,
    paddingRight: 1,
  },
  featuredCardTitle: {
    fontSize: 8.5,
    fontWeight: '700',
    color: '#0D3A20',
    lineHeight: 10.5,
  },
  featuredCardItemCount: {
    fontSize: 7,
    fontWeight: '500',
    color: '#64748B',
    marginTop: 1,
  },
  organicBadgeStamp: {
    width: 15,
    height: 15,
    borderRadius: 7.5,
    backgroundColor: '#DCFCE7',
    borderWidth: 0.5,
    borderColor: '#16A34A',
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: 1,
  },
  organicBadgeText: {
    fontSize: 3.2,
    fontWeight: '800',
    color: '#15803D',
    textAlign: 'center',
    textTransform: 'uppercase',
  },
  featuredImageContainer: {
    width: '100%',
    height: 56,
    justifyContent: 'flex-end',
    alignItems: 'center',
    overflow: 'hidden',
  },
  featuredProductImage: {
    width: '100%',
    height: '100%',
    transform: [{ scale: 1.18 }],
  },

  /* HEALTHY LIFESTYLE BANNER */
  lifestyleBannerCard: {
    marginHorizontal: 16,
    marginTop: 20,
    marginBottom: 20,
    borderRadius: 18,
    backgroundColor: '#D1EEDB',
    borderWidth: 1,
    borderColor: '#C5E6CF',
    position: 'relative',
    height: 130,
    overflow: 'hidden',
    justifyContent: 'center',
  },
  lifestyleBgImage: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    width: '100%',
    height: '100%',
  },
  lifestyleLeftCol: {
    paddingLeft: 14,
    paddingVertical: 10,
    zIndex: 2,
    maxWidth: '47%',
  },
  lifestyleHeadingText: {
    fontSize: 14.5,
    fontWeight: '700',
    color: '#0D3A20',
    lineHeight: 18.5,
    letterSpacing: -0.2,
  },
  lifestyleSubtext: {
    fontSize: 8.5,
    fontWeight: '400',
    color: '#2D5A3C',
    marginTop: 4,
    lineHeight: 12,
  },
  shopNowButton: {
    backgroundColor: '#0F4D2A',
    borderRadius: 16,
    paddingHorizontal: 11,
    paddingVertical: 5,
    alignSelf: 'flex-start',
    marginTop: 8,
    flexDirection: 'row',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.08,
    shadowRadius: 2,
    elevation: 2,
  },
  shopNowBtnText: {
    fontSize: 9.5,
    fontWeight: '600',
    color: '#FFFFFF',
    marginRight: 2,
  },
  scriptFlourishOverlay: {
    position: 'absolute',
    top: 8,
    right: 8,
    zIndex: 3,
    alignItems: 'flex-end',
  },
  scriptFlourishText: {
    fontSize: 8.5,
    fontWeight: '600',
    color: '#1B5E20',
    fontStyle: 'italic',
    lineHeight: 10.5,
    textAlign: 'right',
  },

  /* FIXED BOTTOM NAVIGATION BAR */
  fixedBottomNav: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    height: 56,
    backgroundColor: '#FFFFFF',
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
    borderTopWidth: 1,
    borderTopColor: '#F1F5F9',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -2 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 8,
    zIndex: 100,
  },
  navTabItem: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 4,
  },
  navTabActiveLabel: {
    fontSize: 10.5,
    fontWeight: '700',
    color: '#16A34A',
    marginTop: 2,
  },
  navTabLabel: {
    fontSize: 10.5,
    fontWeight: '500',
    color: '#64748B',
    marginTop: 2,
  },
  navIconContainer: {
    position: 'relative',
  },
  offersRedBadge: {
    position: 'absolute',
    top: -2,
    right: -3,
    width: 7,
    height: 7,
    borderRadius: 3.5,
    backgroundColor: '#EF4444',
    borderWidth: 1,
    borderColor: '#FFFFFF',
  },
});
