import { StyleSheet, Dimensions, Platform } from 'react-native';

const { width: SCREEN_WIDTH } = Dimensions.get('window');

export const styles = StyleSheet.create({
  outerSafeArea: {
    flex: 1,
    backgroundColor: '#FAFDF9',
  },
  screenContainer: {
    flex: 1,
    backgroundColor: '#EEF2F6',
    alignItems: 'center',
  },
  mobileCanvas: {
    width: '100%',
    maxWidth: 480,
    flex: 1,
    backgroundColor: '#FAFDF9',
    position: 'relative',
  },
  scrollContent: {
    paddingBottom: 85,
  },

  // A. TOP HEADER BAR
  topHeaderBar: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 14,
    paddingTop: Platform.OS === 'android' ? 12 : 8,
    paddingBottom: 6,
  },
  locationSelector: {
    flex: 1,
  },
  locationTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  deliveringToText: {
    fontSize: 11,
    fontWeight: '600',
    color: '#64748B',
  },
  locationAddressText: {
    fontSize: 11.5,
    fontWeight: '700',
    color: '#0F2E1E',
    marginTop: 1,
  },
  rightActionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  iconButton: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
  },
  notificationDot: {
    position: 'absolute',
    top: 7,
    right: 8,
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: '#EF4444',
  },
  cartBadge: {
    position: 'absolute',
    top: -3,
    right: -3,
    backgroundColor: '#16A34A',
    borderRadius: 9,
    minWidth: 16,
    height: 16,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 3,
    borderWidth: 1.5,
    borderColor: '#FFFFFF',
  },
  cartBadgeText: {
    color: '#FFFFFF',
    fontSize: 9,
    fontWeight: '700',
  },

  // B. SEARCH BAR
  searchBarContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    marginHorizontal: 12,
    marginTop: 4,
    marginBottom: 6,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    paddingHorizontal: 10,
    height: 40,
    gap: 8,
  },
  searchInput: {
    flex: 1,
    fontSize: 12,
    color: '#0F2E1E',
    paddingVertical: 0,
  },
  qrButton: {
    padding: 2,
  },

  // C. CATEGORY TITLE SECTION
  categoryTitleSection: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 12,
    marginTop: 2,
    marginBottom: 8,
  },
  titleLeftCol: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
    gap: 6,
  },
  backBtn: {
    width: 28,
    height: 28,
    alignItems: 'center',
    justifyContent: 'center',
  },
  titleTexts: {
    flex: 1,
  },
  categoryMainTitle: {
    fontSize: 16,
    fontWeight: '800',
    color: '#0F2E1E',
    letterSpacing: -0.2,
  },
  categorySubtitle: {
    fontSize: 10,
    color: '#64748B',
    marginTop: 1,
  },
  promoPill: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#EAF7EE',
    borderWidth: 1,
    borderColor: '#C6EBD0',
    borderRadius: 18,
    paddingHorizontal: 8,
    paddingVertical: 3,
    gap: 4,
  },
  promoText: {
    fontSize: 9,
    fontWeight: '700',
    color: '#16A34A',
    lineHeight: 11,
    textAlign: 'center',
  },

  // D. HORIZONTALLY SCROLLABLE CATEGORY FILTER ROW
  filterScroll: {
    maxHeight: 100,
    marginBottom: 8,
  },
  filterScrollContent: {
    paddingHorizontal: 8,
    gap: 5,
    alignItems: 'stretch',
  },
  filterItem: {
    width: 56,
    minWidth: 56,
    height: 86,
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 2,
    paddingTop: 5,
    paddingBottom: 5,
    borderRadius: 12,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E2E8F0',
  },
  filterItemActive: {
    borderColor: '#16A34A',
    backgroundColor: '#EAF7EE',
    borderWidth: 1.5,
  },
  filterIconWrap: {
    width: '100%',
    height: 50,
    alignItems: 'center',
    justifyContent: 'center',
  },
  allIconCircle: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: '#DCF4E3',
    alignItems: 'center',
    justifyContent: 'center',
  },
  filterIconImage: {
    width: 50,
    height: 48,
    maxWidth: 52,
    maxHeight: 50,
    resizeMode: 'contain',
    ...(Platform.OS === 'web'
      ? {
          objectFit: 'contain',
          objectPosition: 'center',
        }
      : {}),
  },
  filterLabel: {
    fontSize: 8.5,
    fontWeight: '600',
    color: '#334155',
    textAlign: 'center',
    lineHeight: 10.5,
  },
  filterLabelActive: {
    color: '#16A34A',
    fontWeight: '700',
  },

  // E. HERO BANNER
  heroBannerContainer: {
    backgroundColor: '#EAF8EE',
    borderWidth: 1,
    borderColor: '#D2F0DC',
    borderRadius: 14,
    marginHorizontal: 12,
    marginBottom: 10,
    height: 106,
    position: 'relative',
    overflow: 'hidden',
    justifyContent: 'center',
  },
  heroBannerBgImage: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    width: '100%',
    height: '100%',
  },
  heroBannerContent: {
    width: '45%',
    maxWidth: 160,
    paddingLeft: 12,
    paddingVertical: 8,
    justifyContent: 'center',
    zIndex: 2,
  },
  heroBannerTitle: {
    fontSize: 15,
    fontWeight: '800',
    color: '#0F2E1E',
    lineHeight: 18,
    letterSpacing: -0.2,
  },
  heroBannerSub: {
    fontSize: 9.5,
    color: '#3B6A4C',
    marginTop: 3,
    marginBottom: 8,
    lineHeight: 12,
  },
  heroBannerBtn: {
    alignSelf: 'flex-start',
    backgroundColor: '#16A34A',
    borderRadius: 14,
    paddingHorizontal: 10,
    paddingVertical: 4.5,
  },
  heroBannerBtnText: {
    color: '#FFFFFF',
    fontSize: 10,
    fontWeight: '700',
  },
  heroBannerRightBadges: {
    position: 'absolute',
    right: 10,
    top: 8,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    zIndex: 2,
  },
  farmFreshBadgeText: {
    fontSize: 6.5,
    fontWeight: '800',
    color: '#16A34A',
    textAlign: 'center',
    lineHeight: 7.5,
    marginTop: 13,
    marginLeft: 3,
  },
  eatFreshText: {
    fontSize: 7.5,
    fontWeight: '700',
    color: '#1E6B39',
    lineHeight: 9,
    fontStyle: 'italic',
  },

  // F. FILTER / SORT ROW
  filterSortStrip: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    gap: 6,
    marginBottom: 8,
    flexWrap: 'nowrap',
  },
  filterPillBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 14,
    paddingHorizontal: 7,
    paddingVertical: 4,
    gap: 3,
  },
  filterPillBtnActive: {
    borderColor: '#16A34A',
    backgroundColor: '#EAF7EE',
  },
  filterPillText: {
    fontSize: 10.5,
    fontWeight: '600',
    color: '#334155',
  },
  filterPillTextActive: {
    color: '#16A34A',
    fontWeight: '700',
  },

  // G. PRODUCT COUNT & VIEW TOGGLE
  countViewRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 12,
    marginBottom: 8,
  },
  productCountText: {
    fontSize: 11.5,
    fontWeight: '700',
    color: '#0F2E1E',
  },
  viewToggleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  viewToggleLabel: {
    fontSize: 11,
    color: '#64748B',
    marginRight: 2,
  },
  viewIconBtn: {
    padding: 3,
    borderRadius: 4,
  },
  viewIconBtnActive: {
    backgroundColor: '#EAF7EE',
  },

  // H. 4-COLUMN PRODUCT GRID
  gridContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    paddingHorizontal: 8,
    justifyContent: 'flex-start',
    gap: 6,
  },
  productCard: {
    width: '23.3%',
    backgroundColor: '#FFFFFF',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#EAEFEA',
    padding: 4,
    marginBottom: 4,
    position: 'relative',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'space-between',
  },
  cardImageWrapper: {
    width: '100%',
    height: 58,
    position: 'relative',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 2,
  },
  discountBadge: {
    position: 'absolute',
    top: 0,
    left: 0,
    backgroundColor: '#16A34A',
    borderRadius: 3,
    paddingHorizontal: 2.5,
    paddingVertical: 1,
    zIndex: 2,
  },
  discountText: {
    color: '#FFFFFF',
    fontSize: 6.5,
    fontWeight: '700',
  },
  wishlistBtn: {
    position: 'absolute',
    top: 0,
    right: 0,
    zIndex: 2,
    padding: 2,
  },
  productImage: {
    width: '100%',
    height: '100%',
    maxWidth: 58,
    maxHeight: 58,
    resizeMode: 'contain',
    ...(Platform.OS === 'web'
      ? {
          objectFit: 'contain',
          objectPosition: 'center',
        }
      : {}),
  },
  cardInfo: {
    flex: 1,
  },
  productName: {
    fontSize: 9,
    fontWeight: '700',
    color: '#0F2E1E',
    lineHeight: 11,
  },
  productWeight: {
    fontSize: 7.5,
    color: '#64748B',
    marginTop: 1,
  },
  priceRow: {
    flexDirection: 'row',
    alignItems: 'baseline',
    gap: 2,
    marginTop: 2,
    marginBottom: 4,
  },
  currentPrice: {
    fontSize: 10,
    fontWeight: '800',
    color: '#0F2E1E',
  },
  oldPrice: {
    fontSize: 7.5,
    color: '#94A3B8',
    textDecorationLine: 'line-through',
  },
  addBtn: {
    backgroundColor: '#16A34A',
    borderRadius: 4,
    paddingVertical: 3.5,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 2,
    width: '100%',
  },
  addBtnAdded: {
    backgroundColor: '#0F2E1E',
  },
  addBtnText: {
    color: '#FFFFFF',
    fontSize: 8.5,
    fontWeight: '700',
  },

  // LIST VIEW LAYOUT (WHEN VIEW TOGGLED)
  listContainer: {
    paddingHorizontal: 12,
    gap: 8,
  },
  listCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#EAEFEA',
    padding: 8,
    gap: 10,
  },
  listImageWrap: {
    width: 54,
    height: 54,
    alignItems: 'center',
    justifyContent: 'center',
  },
  listImage: {
    width: 48,
    height: 48,
  },
  listDetails: {
    flex: 1,
  },
  listName: {
    fontSize: 12.5,
    fontWeight: '700',
    color: '#0F2E1E',
  },
  listWeight: {
    fontSize: 10,
    color: '#64748B',
    marginTop: 2,
  },
  listPriceRow: {
    flexDirection: 'row',
    alignItems: 'baseline',
    gap: 4,
    marginTop: 3,
  },
  listPrice: {
    fontSize: 13,
    fontWeight: '800',
    color: '#0F2E1E',
  },
  listOldPrice: {
    fontSize: 10,
    color: '#94A3B8',
    textDecorationLine: 'line-through',
  },
  listAddBtn: {
    backgroundColor: '#16A34A',
    borderRadius: 6,
    paddingHorizontal: 14,
    paddingVertical: 7,
  },
  listAddBtnText: {
    color: '#FFFFFF',
    fontSize: 11,
    fontWeight: '700',
  },

  // J. FIXED BOTTOM NAVIGATION BAR
  bottomNavContainer: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: '#FFFFFF',
    borderTopWidth: 1,
    borderTopColor: '#E2E8F0',
    alignItems: 'center',
    zIndex: 100,
  },
  bottomNavCanvas: {
    width: '100%',
    maxWidth: 480,
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
    paddingTop: 6,
    paddingBottom: Platform.OS === 'ios' ? 18 : 8,
  },
  navTab: {
    alignItems: 'center',
    justifyContent: 'center',
    flex: 1,
    position: 'relative',
  },
  navLabel: {
    fontSize: 9.5,
    fontWeight: '500',
    color: '#64748B',
    marginTop: 2,
  },
  navLabelActive: {
    color: '#16A34A',
    fontWeight: '700',
  },
  offerBadge: {
    position: 'absolute',
    top: -2,
    right: 24,
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: '#EF4444',
  },
});
