import { StyleSheet, Platform } from 'react-native';

export const styles = StyleSheet.create({
  outerSafeArea: {
    flex: 1,
    backgroundColor: '#FAFDF9',
  },
  screenContainer: {
    flex: 1,
    backgroundColor: '#FAFDF9',
    alignItems: 'center',
  },
  mobileCanvas: {
    width: '100%',
    maxWidth: 480,
    flex: 1,
    backgroundColor: '#FAFDF9',
  },
  scrollContent: {
    paddingBottom: 95,
  },

  /* ---------------- TOP HEADER ---------------- */
  topHeaderBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingTop: Platform.OS === 'android' ? 8 : 6,
    paddingBottom: 8,
    backgroundColor: '#FAFDF9',
  },
  locationSelector: {
    flexDirection: 'column',
    justifyContent: 'center',
  },
  locationTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  deliveringToText: {
    fontSize: 13.5,
    fontWeight: '700',
    color: '#0F2E1E',
  },
  locationAddressText: {
    fontSize: 11,
    fontWeight: '500',
    color: '#64748B',
    marginTop: 1,
    marginLeft: 2,
  },
  rightActionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  iconButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#FFFFFF',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    position: 'relative',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.04,
    shadowRadius: 2,
    elevation: 1,
  },
  notificationDot: {
    position: 'absolute',
    top: 7,
    right: 7,
    width: 7,
    height: 7,
    borderRadius: 3.5,
    backgroundColor: '#EF4444',
  },
  cartBadge: {
    position: 'absolute',
    top: -3,
    right: -3,
    backgroundColor: '#16A34A',
    minWidth: 17,
    height: 17,
    borderRadius: 8.5,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 3,
    borderWidth: 1.5,
    borderColor: '#FFFFFF',
  },
  cartBadgeText: {
    color: '#FFFFFF',
    fontSize: 9.5,
    fontWeight: '800',
  },

  /* ---------------- SEARCH BAR ---------------- */
  searchBarContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    marginHorizontal: 16,
    marginTop: 6,
    marginBottom: 10,
    paddingHorizontal: 12,
    height: 42,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.03,
    shadowRadius: 3,
    elevation: 1,
  },
  searchInput: {
    flex: 1,
    marginLeft: 8,
    marginRight: 6,
    fontSize: 12.5,
    color: '#1E293B',
    paddingVertical: 0,
    ...(Platform.OS === 'web' ? { outlineStyle: 'none' } : {}),
  },
  qrButton: {
    padding: 4,
  },

  /* ---------------- CATEGORY TITLE & PROMO HEADER ---------------- */
  categoryTitleSection: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    marginVertical: 4,
  },
  titleLeftCol: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
    marginRight: 8,
  },
  backBtn: {
    paddingRight: 8,
    paddingVertical: 4,
  },
  titleTexts: {
    flex: 1,
  },
  categoryMainTitle: {
    fontSize: 17,
    fontWeight: '800',
    color: '#0F2E1E',
    letterSpacing: -0.3,
  },
  categorySubtitle: {
    fontSize: 10.5,
    color: '#64748B',
    marginTop: 2,
    fontWeight: '500',
  },
  promoPill: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#EDF8EE',
    borderWidth: 1,
    borderColor: '#D2EFD7',
    borderRadius: 14,
    paddingHorizontal: 9,
    paddingVertical: 5,
    gap: 6,
  },
  promoText: {
    fontSize: 9.5,
    fontWeight: '800',
    color: '#14532D',
    lineHeight: 12,
  },

  /* ---------------- HORIZONTAL CATEGORY FILTER ROW ---------------- */
  filterScroll: {
    marginTop: 10,
    marginBottom: 10,
  },
  filterScrollContent: {
    paddingHorizontal: 14,
    gap: 8,
    flexDirection: 'row',
    alignItems: 'center',
  },
  filterItem: {
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 12,
    paddingHorizontal: 10,
    paddingVertical: 6,
    minWidth: 54,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.02,
    shadowRadius: 2,
    elevation: 1,
  },
  filterItemActive: {
    backgroundColor: '#EDF8EE',
    borderColor: '#16A34A',
    borderWidth: 1.5,
  },
  filterIconWrap: {
    width: 28,
    height: 28,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 4,
  },
  filterIconImage: {
    width: 26,
    height: 26,
  },
  filterLabel: {
    fontSize: 9.5,
    fontWeight: '600',
    color: '#475569',
    textAlign: 'center',
  },
  filterLabelActive: {
    color: '#16A34A',
    fontWeight: '800',
  },

  /* ---------------- HERO BANNER ---------------- */
  heroBannerContainer: {
    marginHorizontal: 14,
    marginTop: 4,
    marginBottom: 14,
    borderRadius: 16,
    backgroundColor: '#E4F4E2',
    overflow: 'hidden',
    position: 'relative',
    height: 114,
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#D4ECD2',
  },
  heroBannerBgImage: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    width: '100%',
    height: '100%',
  },
  heroBannerContent: {
    width: '58%',
    paddingLeft: 14,
    paddingVertical: 10,
    justifyContent: 'center',
    zIndex: 2,
  },
  heroBannerTitle: {
    fontSize: 16,
    fontWeight: '800',
    color: '#0B3B24',
    lineHeight: 19,
    letterSpacing: -0.3,
  },
  heroBannerSub: {
    fontSize: 9.5,
    color: '#2D5339',
    marginTop: 3,
    lineHeight: 13,
    fontWeight: '500',
  },
  heroBannerBtn: {
    alignSelf: 'flex-start',
    backgroundColor: '#123C24',
    borderRadius: 14,
    paddingHorizontal: 11,
    paddingVertical: 5,
    marginTop: 8,
  },
  heroBannerBtnText: {
    color: '#FFFFFF',
    fontSize: 10,
    fontWeight: '700',
  },

  /* ---------------- SECTION HEADER ---------------- */
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    marginBottom: 8,
  },
  sectionTitle: {
    fontSize: 15,
    fontWeight: '800',
    color: '#0F2E1E',
    letterSpacing: -0.2,
  },
  seeAllButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 3,
  },
  seeAllText: {
    fontSize: 11.5,
    fontWeight: '700',
    color: '#16A34A',
  },

  /* ---------------- 4-COLUMN PRODUCT GRID ---------------- */
  productGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    paddingHorizontal: 12,
    gap: 6,
    justifyContent: 'space-between',
    marginBottom: 16,
  },
  productCard: {
    width: '23.6%',
    minWidth: 74,
    backgroundColor: '#FFFFFF',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#E8ECE9',
    padding: 5,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.03,
    shadowRadius: 2,
    elevation: 1,
    position: 'relative',
    justifyContent: 'space-between',
  },
  discountBadge: {
    position: 'absolute',
    top: 4,
    left: 4,
    backgroundColor: '#16A34A',
    borderRadius: 4,
    paddingHorizontal: 3.5,
    paddingVertical: 1.5,
    zIndex: 2,
  },
  discountText: {
    color: '#FFFFFF',
    fontSize: 6.5,
    fontWeight: '800',
  },
  productImageWrap: {
    width: '100%',
    height: 48,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 2,
    marginBottom: 3,
  },
  productImage: {
    width: '90%',
    height: '90%',
  },
  productInfo: {
    marginBottom: 4,
  },
  productName: {
    fontSize: 9.5,
    fontWeight: '700',
    color: '#0F172A',
    lineHeight: 12,
  },
  productVariety: {
    fontSize: 7.5,
    color: '#64748B',
    lineHeight: 10,
  },
  productUnit: {
    fontSize: 7.5,
    color: '#94A3B8',
    marginTop: 1,
  },
  priceRow: {
    flexDirection: 'row',
    alignItems: 'baseline',
    gap: 3,
    marginTop: 2,
    marginBottom: 4,
  },
  productPrice: {
    fontSize: 10,
    fontWeight: '800',
    color: '#0F172A',
  },
  productOldPrice: {
    fontSize: 7.5,
    color: '#94A3B8',
    textDecorationLine: 'line-through',
  },
  addBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#16A34A',
    borderRadius: 6,
    paddingVertical: 3.5,
    paddingHorizontal: 2,
    gap: 3,
  },
  addBtnAdded: {
    backgroundColor: '#15803D',
  },
  addBtnText: {
    fontSize: 8.5,
    fontWeight: '800',
    color: '#FFFFFF',
  },

  /* ---------------- ORGANIC BANNER ---------------- */
  organicBannerContainer: {
    marginHorizontal: 14,
    marginTop: 2,
    marginBottom: 14,
    borderRadius: 16,
    backgroundColor: '#EFF7E8',
    overflow: 'hidden',
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#DFEED6',
    minHeight: 105,
  },
  organicBannerLeft: {
    flex: 1.15,
    paddingLeft: 14,
    paddingVertical: 12,
    justifyContent: 'center',
    zIndex: 2,
  },
  organicBannerTitle: {
    fontSize: 15,
    fontWeight: '800',
    color: '#0B3B24',
    lineHeight: 18,
    letterSpacing: -0.3,
  },
  organicBannerSub: {
    fontSize: 9.5,
    color: '#2D5339',
    marginTop: 4,
    lineHeight: 13,
    fontWeight: '500',
  },
  organicBannerBtn: {
    alignSelf: 'flex-start',
    backgroundColor: '#123C24',
    borderRadius: 14,
    paddingHorizontal: 11,
    paddingVertical: 5.5,
    marginTop: 8,
  },
  organicBannerBtnText: {
    color: '#FFFFFF',
    fontSize: 9.5,
    fontWeight: '700',
  },
  organicBannerRight: {
    flex: 1,
    height: 105,
    justifyContent: 'center',
    alignItems: 'flex-end',
  },
  organicBannerImage: {
    width: '100%',
    height: '100%',
  },

  /* ---------------- BOTTOM NAV BAR ---------------- */
  bottomNavContainer: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    alignItems: 'center',
    backgroundColor: 'transparent',
  },
  bottomNavCanvas: {
    width: '100%',
    maxWidth: 480,
    backgroundColor: '#FFFFFF',
    borderTopWidth: 1,
    borderTopColor: '#E2E8F0',
    paddingVertical: 6,
    paddingBottom: Platform.OS === 'ios' ? 18 : 6,
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 8,
  },
  navTab: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 10,
    position: 'relative',
  },
  navLabel: {
    fontSize: 10,
    color: '#64748B',
    marginTop: 3,
    fontWeight: '600',
  },
  navLabelActive: {
    color: '#16A34A',
    fontWeight: '800',
  },
  offerBadge: {
    position: 'absolute',
    top: -2,
    right: 6,
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: '#EF4444',
  },
});
