import { StyleSheet, Dimensions, Platform } from 'react-native';

const { width: SCREEN_WIDTH } = Dimensions.get('window');

export const styles = StyleSheet.create({
  outerSafeArea: {
    flex: 1,
    backgroundColor: '#FAFDF9',
  },
  screenContainer: {
    flex: 1,
    backgroundColor: '#EEF2F6',
    alignItems: 'center',
  },
  mobileCanvas: {
    width: '100%',
    maxWidth: 480,
    flex: 1,
    backgroundColor: '#FAFDF9',
    position: 'relative',
  },
  scrollContent: {
    paddingBottom: 95,
  },

  // A. TOP CLOSE ROW & SUCCESS HEADER
  topCloseRow: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    paddingHorizontal: 14,
    paddingTop: Platform.OS === 'android' ? 12 : 8,
  },
  closeBtn: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    alignItems: 'center',
    justifyContent: 'center',
  },
  successHeaderBlock: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 14,
    marginTop: 4,
    marginBottom: 12,
    gap: 12,
  },
  successBadgeWrap: {
    width: 62,
    height: 62,
    borderRadius: 31,
    backgroundColor: '#EAF7EE',
    borderWidth: 1.5,
    borderColor: '#A7F3D0',
    borderStyle: 'dashed',
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
  },
  successInnerCircle: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: '#16A34A',
    alignItems: 'center',
    justifyContent: 'center',
  },
  sparkle1: {
    position: 'absolute',
    top: 2,
    right: 4,
    width: 5,
    height: 5,
    borderRadius: 2.5,
    backgroundColor: '#F59E0B',
  },
  sparkle2: {
    position: 'absolute',
    bottom: 4,
    left: 2,
    width: 4,
    height: 4,
    borderRadius: 2,
    backgroundColor: '#10B981',
  },
  sparkle3: {
    position: 'absolute',
    top: 6,
    left: 4,
    width: 3,
    height: 3,
    borderRadius: 1.5,
    backgroundColor: '#3B82F6',
  },
  successTextCol: {
    flex: 1,
  },
  successTitle: {
    fontSize: 18,
    fontWeight: '800',
    color: '#0F2E1E',
    letterSpacing: -0.2,
  },
  successThankYou: {
    fontSize: 11,
    fontWeight: '600',
    color: '#334155',
    marginTop: 2,
  },
  successSubText: {
    fontSize: 9.5,
    color: '#64748B',
    marginTop: 1,
    lineHeight: 13,
  },

  // B. ORDER INFO 3-COL CARD
  orderInfoCard: {
    backgroundColor: '#EAF7EE',
    borderWidth: 1,
    borderColor: '#C6EBD0',
    borderRadius: 12,
    marginHorizontal: 12,
    marginBottom: 14,
    paddingVertical: 10,
    paddingHorizontal: 12,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  orderInfoCol: {
    flex: 1,
  },
  orderInfoColBorder: {
    borderLeftWidth: 1,
    borderLeftColor: '#D1EAD7',
    paddingLeft: 10,
  },
  orderInfoLabel: {
    fontSize: 9,
    color: '#64748B',
    fontWeight: '500',
  },
  orderInfoValue: {
    fontSize: 11,
    fontWeight: '800',
    color: '#0F2E1E',
    marginTop: 2,
  },

  // C. ORDER TRACKING SECTION
  sectionBlock: {
    paddingHorizontal: 12,
    marginBottom: 14,
  },
  sectionHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  sectionHeading: {
    fontSize: 13,
    fontWeight: '800',
    color: '#0F2E1E',
  },
  sectionActionLink: {
    fontSize: 11,
    fontWeight: '700',
    color: '#16A34A',
  },
  trackingFlowContainer: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    paddingHorizontal: 6,
    marginTop: 4,
    marginBottom: 4,
  },
  trackStepItem: {
    alignItems: 'center',
    width: 68,
  },
  trackIconCircleActive: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#16A34A',
    alignItems: 'center',
    justifyContent: 'center',
  },
  trackIconCircleInactive: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#F1F5F9',
    borderWidth: 1.5,
    borderColor: '#CBD5E1',
    alignItems: 'center',
    justifyContent: 'center',
  },
  trackStepTitleActive: {
    fontSize: 9.5,
    fontWeight: '800',
    color: '#16A34A',
    textAlign: 'center',
    marginTop: 4,
  },
  trackStepTitleInactive: {
    fontSize: 9.5,
    fontWeight: '700',
    color: '#0F2E1E',
    textAlign: 'center',
    marginTop: 4,
  },
  trackStepSub: {
    fontSize: 7.5,
    color: '#64748B',
    textAlign: 'center',
    marginTop: 1,
    lineHeight: 9.5,
  },
  trackConnectingLineCompleted: {
    flex: 1,
    height: 2,
    backgroundColor: '#16A34A',
    marginTop: 15,
    marginHorizontal: -8,
  },
  trackConnectingLinePending: {
    flex: 1,
    height: 2,
    backgroundColor: '#CBD5E1',
    marginTop: 15,
    marginHorizontal: -8,
  },

  // D. DELIVERY DETAILS CARD
  deliveryDetailsCard: {
    backgroundColor: '#F4FAF6',
    borderWidth: 1,
    borderColor: '#D4EBDC',
    borderRadius: 12,
    padding: 10,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  deliveryDetailsColLeft: {
    flex: 1.2,
    flexDirection: 'row',
    gap: 8,
    paddingRight: 8,
  },
  deliveryDetailsColRight: {
    flex: 1,
    flexDirection: 'row',
    gap: 8,
    borderLeftWidth: 1,
    borderLeftColor: '#E2E8F0',
    paddingLeft: 8,
  },
  detailsIconCircle: {
    width: 26,
    height: 26,
    borderRadius: 13,
    backgroundColor: '#EAF7EE',
    alignItems: 'center',
    justifyContent: 'center',
  },
  detailsColText: {
    flex: 1,
  },
  detailsTag: {
    fontSize: 8.5,
    color: '#16A34A',
    fontWeight: '600',
  },
  detailsTitle: {
    fontSize: 11,
    fontWeight: '800',
    color: '#0F2E1E',
    marginTop: 1,
  },
  detailsAddressLine: {
    fontSize: 8.5,
    color: '#64748B',
    marginTop: 1,
    lineHeight: 11.5,
  },
  detailsPhone: {
    fontSize: 9,
    fontWeight: '700',
    color: '#0F2E1E',
    marginTop: 2,
  },
  detailsEstimateTag: {
    fontSize: 8.5,
    color: '#64748B',
    fontWeight: '500',
  },
  detailsEstimateTime: {
    fontSize: 10.5,
    fontWeight: '800',
    color: '#0F2E1E',
    marginTop: 1,
  },
  detailsFreeTag: {
    fontSize: 9,
    fontWeight: '800',
    color: '#16A34A',
    marginTop: 2,
  },

  // E. ITEMS IN THIS ORDER (4 CARDS ROW)
  orderItemsGrid: {
    flexDirection: 'row',
    gap: 6,
    justifyContent: 'space-between',
  },
  orderItemSmallCard: {
    flex: 1,
    backgroundColor: '#FFFFFF',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#EAEFEA',
    padding: 6,
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  orderItemImgWrap: {
    width: '100%',
    height: 44,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 2,
  },
  orderItemImg: {
    width: 40,
    height: 40,
    resizeMode: 'contain',
    ...(Platform.OS === 'web'
      ? {
          objectFit: 'contain',
          objectPosition: 'center',
        }
      : {}),
  },
  orderItemName: {
    fontSize: 9,
    fontWeight: '700',
    color: '#0F2E1E',
    width: '100%',
    textAlign: 'left',
  },
  orderItemUnit: {
    fontSize: 7.5,
    color: '#64748B',
    width: '100%',
    textAlign: 'left',
    marginTop: 0.5,
  },
  orderItemPriceRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 3,
    width: '100%',
    marginTop: 2,
  },
  orderItemCurrentPrice: {
    fontSize: 10,
    fontWeight: '800',
    color: '#0F2E1E',
  },
  orderItemOldPrice: {
    fontSize: 8,
    color: '#94A3B8',
    textDecorationLine: 'line-through',
  },

  // F. ACTION BUTTONS ROW
  actionButtonsRow: {
    flexDirection: 'row',
    paddingHorizontal: 12,
    marginBottom: 12,
    gap: 8,
  },
  viewOrderDetailsBtn: {
    flex: 1,
    backgroundColor: '#EAF7EE',
    borderWidth: 1,
    borderColor: '#16A34A',
    borderRadius: 8,
    paddingVertical: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 5,
  },
  viewOrderDetailsBtnText: {
    fontSize: 11,
    fontWeight: '700',
    color: '#16A34A',
  },
  continueShoppingBtn: {
    flex: 1,
    backgroundColor: '#16A34A',
    borderRadius: 8,
    paddingVertical: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 5,
  },
  continueShoppingBtnText: {
    fontSize: 11,
    fontWeight: '700',
    color: '#FFFFFF',
  },

  // G. PROMOTIONAL BANNER (GOOD FOOD HAPPIER YOU)
  promoBannerCard: {
    backgroundColor: '#EBF7EE',
    borderWidth: 1,
    borderColor: '#C6EBD0',
    borderRadius: 12,
    marginHorizontal: 12,
    marginBottom: 12,
    padding: 10,
    position: 'relative',
    overflow: 'hidden',
    minHeight: 110,
  },
  promoContentCol: {
    width: '58%',
    zIndex: 2,
  },
  promoMainTitle: {
    fontSize: 14,
    fontWeight: '900',
    color: '#0F2E1E',
    lineHeight: 17,
  },
  promoSubText: {
    fontSize: 8.5,
    color: '#334155',
    marginTop: 3,
    marginBottom: 8,
    lineHeight: 11.5,
  },
  shopMoreBtn: {
    backgroundColor: '#0F2E1E',
    borderRadius: 14,
    paddingHorizontal: 10,
    paddingVertical: 5,
    alignSelf: 'flex-start',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  shopMoreBtnText: {
    fontSize: 9.5,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  promoBasketImg: {
    position: 'absolute',
    right: -10,
    bottom: -5,
    width: 170,
    height: 105,
    resizeMode: 'contain',
    zIndex: 1,
  },

  // H. NEED HELP CARD
  needHelpCard: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 10,
    marginHorizontal: 12,
    marginBottom: 14,
    padding: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  needHelpLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    flex: 1,
  },
  needHelpTextCol: {
    flex: 1,
  },
  needHelpTitle: {
    fontSize: 11,
    fontWeight: '800',
    color: '#0F2E1E',
  },
  needHelpSub: {
    fontSize: 8.5,
    color: '#64748B',
    marginTop: 1,
  },
  getHelpBtn: {
    backgroundColor: '#EAF7EE',
    borderWidth: 1,
    borderColor: '#C6EBD0',
    borderRadius: 6,
    paddingHorizontal: 8,
    paddingVertical: 4,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 3,
  },
  getHelpBtnText: {
    fontSize: 9.5,
    fontWeight: '700',
    color: '#16A34A',
  },

  // I. FIXED BOTTOM NAVIGATION
  bottomNavContainer: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: '#FFFFFF',
    borderTopWidth: 1,
    borderTopColor: '#E2E8F0',
    alignItems: 'center',
    zIndex: 100,
  },
  bottomNavCanvas: {
    width: '100%',
    maxWidth: 480,
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
    paddingTop: 6,
    paddingBottom: Platform.OS === 'ios' ? 18 : 8,
  },
  navTab: {
    alignItems: 'center',
    justifyContent: 'center',
    flex: 1,
    position: 'relative',
  },
  navLabel: {
    fontSize: 9.5,
    fontWeight: '500',
    color: '#64748B',
    marginTop: 2,
  },
  navLabelActive: {
    color: '#16A34A',
    fontWeight: '700',
  },
  offerBadge: {
    position: 'absolute',
    top: -2,
    right: 24,
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: '#EF4444',
  },

  // J. MODAL STYLES
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(15, 23, 42, 0.6)',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 16,
  },
  modalContentBox: {
    width: '100%',
    maxWidth: 380,
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    padding: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 12,
    elevation: 8,
  },
  modalHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#F1F5F9',
    paddingBottom: 8,
  },
  modalTitle: {
    fontSize: 14,
    fontWeight: '800',
    color: '#0F2E1E',
  },
  modalCloseIconBtn: {
    padding: 4,
  },
  modalReceiptSection: {
    backgroundColor: '#FAFDF9',
    borderWidth: 1,
    borderColor: '#EAEFEA',
    borderRadius: 10,
    padding: 10,
    marginBottom: 8,
  },
  modalSectionLabel: {
    fontSize: 10,
    color: '#64748B',
    fontWeight: '600',
    marginBottom: 4,
  },
  modalBodyText: {
    fontSize: 10.5,
    color: '#475569',
    lineHeight: 14,
  },
  modalBodyTextBold: {
    fontSize: 11,
    fontWeight: '700',
    color: '#0F2E1E',
  },
  modalItemRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 3,
  },
  modalItemName: {
    fontSize: 10.5,
    color: '#0F2E1E',
    fontWeight: '600',
  },
  modalItemPrice: {
    fontSize: 11,
    color: '#0F2E1E',
    fontWeight: '700',
  },
  modalPriceHighlight: {
    fontSize: 14,
    fontWeight: '900',
    color: '#16A34A',
  },
  modalPrimaryBtn: {
    backgroundColor: '#16A34A',
    borderRadius: 8,
    paddingVertical: 10,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 10,
  },
  modalPrimaryBtnText: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '700',
  },
  helpActionCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F8FAF8',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 8,
    padding: 10,
  },
  helpCardTitle: {
    fontSize: 11,
    fontWeight: '700',
    color: '#0F2E1E',
  },
  helpCardSub: {
    fontSize: 9,
    color: '#64748B',
    marginTop: 1,
  },
  modalOfferCard: {
    backgroundColor: '#EAF7EE',
    borderWidth: 1,
    borderColor: '#C6EBD0',
    borderRadius: 8,
    padding: 10,
  },
  modalOfferTitle: {
    fontSize: 11.5,
    fontWeight: '800',
    color: '#16A34A',
  },
  modalOfferSub: {
    fontSize: 9.5,
    color: '#334155',
    marginTop: 2,
  },
});
