import { StyleSheet, Dimensions, Platform } from 'react-native';

const { width: SCREEN_WIDTH } = Dimensions.get('window');

export const styles = StyleSheet.create({
  outerSafeArea: {
    flex: 1,
    backgroundColor: '#FAFDF9',
  },
  screenContainer: {
    flex: 1,
    backgroundColor: '#EEF2F6',
    alignItems: 'center',
  },
  mobileCanvas: {
    width: '100%',
    maxWidth: 480,
    flex: 1,
    backgroundColor: '#FAFDF9',
    position: 'relative',
  },
  scrollContent: {
    paddingBottom: 95,
  },

  // A. TOP HEADER BAR
  topHeaderBar: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 14,
    paddingTop: Platform.OS === 'android' ? 12 : 8,
    paddingBottom: 6,
  },
  locationSelector: {
    flex: 1,
  },
  locationTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  deliveringToText: {
    fontSize: 11,
    fontWeight: '600',
    color: '#64748B',
  },
  locationAddressText: {
    fontSize: 11.5,
    fontWeight: '700',
    color: '#0F2E1E',
    marginTop: 1,
  },
  rightActionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  iconButton: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
  },
  notificationDot: {
    position: 'absolute',
    top: 7,
    right: 8,
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: '#EF4444',
  },
  cartBadge: {
    position: 'absolute',
    top: -3,
    right: -3,
    backgroundColor: '#16A34A',
    borderRadius: 9,
    minWidth: 16,
    height: 16,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 3,
    borderWidth: 1.5,
    borderColor: '#FFFFFF',
  },
  cartBadgeText: {
    color: '#FFFFFF',
    fontSize: 9,
    fontWeight: '700',
  },

  // B. USER PROFILE CARD
  profileHeaderCard: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 14,
    paddingVertical: 10,
    marginTop: 2,
    marginBottom: 8,
  },
  profileLeftCol: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    flex: 1,
  },
  avatarContainer: {
    position: 'relative',
    width: 54,
    height: 54,
  },
  avatarImage: {
    width: 54,
    height: 54,
    borderRadius: 27,
    backgroundColor: '#E2E8F0',
  },
  cameraIconBadge: {
    position: 'absolute',
    bottom: 0,
    right: 0,
    width: 18,
    height: 18,
    borderRadius: 9,
    backgroundColor: '#16A34A',
    borderWidth: 1.5,
    borderColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  userInfoCol: {
    flex: 1,
  },
  userNameText: {
    fontSize: 16,
    fontWeight: '800',
    color: '#0F2E1E',
  },
  userPhoneText: {
    fontSize: 10.5,
    color: '#475569',
    fontWeight: '600',
    marginTop: 1,
  },
  userEmailText: {
    fontSize: 9.5,
    color: '#64748B',
    marginTop: 0.5,
  },
  editProfileBtn: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#16A34A',
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 6,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  editProfileBtnText: {
    fontSize: 10.5,
    fontWeight: '700',
    color: '#16A34A',
  },

  // C. GOLD MEMBER BANNER
  goldMemberBanner: {
    backgroundColor: '#F3FBF5',
    borderWidth: 1,
    borderColor: '#C6EBD0',
    borderRadius: 12,
    marginHorizontal: 12,
    marginBottom: 14,
    padding: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    position: 'relative',
    overflow: 'hidden',
  },
  goldLeftCol: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    flex: 1,
    zIndex: 2,
  },
  crownIconWrap: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#FEF3C7',
    alignItems: 'center',
    justifyContent: 'center',
  },
  goldTitle: {
    fontSize: 12,
    fontWeight: '800',
    color: '#0F2E1E',
  },
  goldSub: {
    fontSize: 9.5,
    color: '#2E693D',
    marginTop: 1,
  },
  viewBenefitsBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 2,
    zIndex: 2,
  },
  viewBenefitsText: {
    fontSize: 10,
    fontWeight: '700',
    color: '#16A34A',
  },

  // D. MY ORDERS SECTION
  sectionBlock: {
    paddingHorizontal: 12,
    marginBottom: 12,
  },
  sectionHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  sectionHeading: {
    fontSize: 13,
    fontWeight: '800',
    color: '#0F2E1E',
  },
  sectionActionLink: {
    fontSize: 11,
    fontWeight: '700',
    color: '#16A34A',
  },
  ordersActionGrid: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 6,
  },
  orderActionCard: {
    flex: 1,
    backgroundColor: '#FFFFFF',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#EAEFEA',
    paddingVertical: 10,
    paddingHorizontal: 4,
    alignItems: 'center',
    justifyContent: 'center',
  },
  orderActionIconCircle: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: '#EAF7EE',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 4,
  },
  orderActionTitle: {
    fontSize: 9,
    fontWeight: '700',
    color: '#0F2E1E',
    textAlign: 'center',
  },
  orderActionCount: {
    fontSize: 8,
    color: '#64748B',
    marginTop: 1,
  },

  // E. MENU LIST CARD
  menuCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#EAEFEA',
    marginHorizontal: 12,
    marginBottom: 12,
    paddingHorizontal: 12,
  },
  menuItemRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#F1F5F9',
  },
  menuItemRowLast: {
    borderBottomWidth: 0,
  },
  menuItemLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    flex: 1,
  },
  menuIconWrap: {
    width: 24,
    height: 24,
    alignItems: 'center',
    justifyContent: 'center',
  },
  menuTexts: {
    flex: 1,
  },
  menuTitle: {
    fontSize: 11.5,
    fontWeight: '700',
    color: '#0F2E1E',
  },
  menuSubtitle: {
    fontSize: 9,
    color: '#64748B',
    marginTop: 1,
  },
  menuRight: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  menuBadge: {
    backgroundColor: '#EAF7EE',
    borderRadius: 10,
    paddingHorizontal: 8,
    paddingVertical: 2,
  },
  menuBadgeText: {
    fontSize: 9,
    fontWeight: '700',
    color: '#16A34A',
  },

  // F. LOGOUT BUTTON
  logoutBtn: {
    backgroundColor: '#FFF5F5',
    borderWidth: 1,
    borderColor: '#FECACA',
    borderRadius: 10,
    marginHorizontal: 12,
    marginBottom: 14,
    paddingVertical: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
  },
  logoutBtnText: {
    fontSize: 11.5,
    fontWeight: '700',
    color: '#EF4444',
  },

  // G. PROMOTIONAL BANNER: GOOD FOOD HAPPIER YOU
  promoBannerCard: {
    backgroundColor: '#EBF7EE',
    borderWidth: 1,
    borderColor: '#C6EBD0',
    borderRadius: 12,
    marginHorizontal: 12,
    marginBottom: 14,
    padding: 10,
    position: 'relative',
    overflow: 'hidden',
    minHeight: 110,
  },
  promoContentCol: {
    width: '58%',
    zIndex: 2,
  },
  promoMainTitle: {
    fontSize: 14,
    fontWeight: '900',
    color: '#0F2E1E',
    lineHeight: 17,
  },
  promoSubText: {
    fontSize: 8.5,
    color: '#334155',
    marginTop: 3,
    marginBottom: 8,
    lineHeight: 11.5,
  },
  shopMoreBtn: {
    backgroundColor: '#0F2E1E',
    borderRadius: 14,
    paddingHorizontal: 10,
    paddingVertical: 5,
    alignSelf: 'flex-start',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  shopMoreBtnText: {
    fontSize: 9.5,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  promoBasketImg: {
    position: 'absolute',
    right: -10,
    bottom: -5,
    width: 170,
    height: 105,
    resizeMode: 'contain',
    zIndex: 1,
  },

  // H. FIXED BOTTOM NAVIGATION
  bottomNavContainer: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: '#FFFFFF',
    borderTopWidth: 1,
    borderTopColor: '#E2E8F0',
    alignItems: 'center',
    zIndex: 100,
  },
  bottomNavCanvas: {
    width: '100%',
    maxWidth: 480,
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
    paddingTop: 6,
    paddingBottom: Platform.OS === 'ios' ? 18 : 8,
  },
  navTab: {
    alignItems: 'center',
    justifyContent: 'center',
    flex: 1,
    position: 'relative',
  },
  navLabel: {
    fontSize: 9.5,
    fontWeight: '500',
    color: '#64748B',
    marginTop: 2,
  },
  navLabelActive: {
    color: '#16A34A',
    fontWeight: '700',
  },
  offerBadge: {
    position: 'absolute',
    top: -2,
    right: 24,
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: '#EF4444',
  },

  // I. INTERACTIVE MODAL STYLES
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(15, 23, 42, 0.6)',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 16,
  },
  modalContentBox: {
    width: '100%',
    maxWidth: 380,
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    padding: 16,
  },
  modalHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#F1F5F9',
    paddingBottom: 8,
  },
  modalTitle: {
    fontSize: 14,
    fontWeight: '800',
    color: '#0F2E1E',
  },
  modalCloseBtn: {
    padding: 4,
  },
  modalBodyText: {
    fontSize: 11,
    color: '#475569',
    lineHeight: 15,
  },
  modalPrimaryBtn: {
    backgroundColor: '#16A34A',
    borderRadius: 8,
    paddingVertical: 10,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 12,
  },
  modalPrimaryBtnText: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '700',
  },
});
