/**
 * Freshora Database Seeder
 * Seeds categories, products, quantity options, demo user, address, initial cart, and order.
 */

import bcrypt from 'bcryptjs';
import {
  User,
  Category,
  Product,
  ProductQuantityOption,
  Address,
  Cart,
  CartItem,
  Wishlist,
  Order,
  OrderItem,
} from '../app/models/index.js';

export async function seedDatabase() {
  try {
    console.log('🌱 Starting Freshora database seed...');

    // 1. Seed Categories
    const categoriesData = [
      {
        id: 1,
        name: 'Fruits & Vegetables',
        slug: 'fruits-vegetables',
        item_count_text: '500+ items',
        description: 'Fresh produce for a healthier you',
        bg_color: '#EDF7ED',
        border_color: '#D6ECD7',
        image_url: 'cat_grid_fruits.jpg',
        is_featured: false,
        display_order: 1,
      },
      {
        id: 2,
        name: 'Dairy & Breakfast',
        slug: 'dairy-breakfast',
        item_count_text: '300+ items',
        description: 'Milk, cheese, eggs, cereals and more',
        bg_color: '#EBF5FB',
        border_color: '#D6EAF8',
        image_url: 'cat_grid_dairy.jpg',
        is_featured: false,
        display_order: 2,
      },
      {
        id: 3,
        name: 'Snacks & Beverages',
        slug: 'snacks-beverages',
        item_count_text: '400+ items',
        description: 'Chips, cookies, drinks and more',
        bg_color: '#FEF3E8',
        border_color: '#FDE4CF',
        image_url: 'cat_grid_snacks.jpg',
        is_featured: false,
        display_order: 3,
      },
      {
        id: 4,
        name: 'Atta, Rice & Staples',
        slug: 'atta-rice-staples',
        item_count_text: '300+ items',
        description: 'Daily essentials for your kitchen',
        bg_color: '#FAF4EB',
        border_color: '#F3E7D5',
        image_url: 'cat_grid_staples.jpg',
        is_featured: false,
        display_order: 4,
      },
      {
        id: 5,
        name: 'Household Essentials',
        slug: 'household-essentials',
        item_count_text: '250+ items',
        description: 'Cleaning and home care products',
        bg_color: '#E8F4F8',
        border_color: '#D3EBF2',
        image_url: 'cat_grid_household.jpg',
        is_featured: false,
        display_order: 5,
      },
      {
        id: 6,
        name: 'Personal Care',
        slug: 'personal-care',
        item_count_text: '300+ items',
        description: 'Beauty and hygiene essentials',
        bg_color: '#FDF2F4',
        border_color: '#FADEE3',
        image_url: 'cat_grid_personal.jpg',
        is_featured: false,
        display_order: 6,
      },
      {
        id: 7,
        name: 'Baby Care',
        slug: 'baby-care',
        item_count_text: '200+ items',
        description: 'Gentle care for your little one',
        bg_color: '#E8F6F6',
        border_color: '#D1EEEE',
        image_url: 'cat_grid_baby.jpg',
        is_featured: false,
        display_order: 7,
      },
      {
        id: 8,
        name: 'Pet Care',
        slug: 'pet-care',
        item_count_text: '150+ items',
        description: 'Food and accessories for your pets',
        bg_color: '#FFF8E7',
        border_color: '#FDF0CA',
        image_url: 'cat_grid_pet.jpg',
        is_featured: false,
        display_order: 8,
      },
      {
        id: 9,
        name: 'Organic Products',
        slug: 'organic-products',
        item_count_text: '120+ items',
        description: 'Naturally good, always',
        bg_color: '#EDF7ED',
        border_color: '#D6ECD7',
        image_url: 'cat_feat_organic.jpg',
        is_featured: true,
        badge_text: 'ORGANIC',
        display_order: 9,
      },
      {
        id: 10,
        name: 'Healthy Snacks',
        slug: 'healthy-snacks',
        item_count_text: '100+ items',
        description: 'Nutritious & delicious bites',
        bg_color: '#FAF4EB',
        border_color: '#F3E7D5',
        image_url: 'cat_feat_snacks.png',
        is_featured: true,
        display_order: 10,
      },
      {
        id: 11,
        name: 'Beverages',
        slug: 'beverages',
        item_count_text: '180+ items',
        description: 'Refreshing juices and drinks',
        bg_color: '#EBF5FB',
        border_color: '#D6EAF8',
        image_url: 'cat_feat_beverages.png',
        is_featured: true,
        display_order: 11,
      },
    ];

    for (const cat of categoriesData) {
      await Category.findOrCreate({
        where: { slug: cat.slug },
        defaults: cat,
      });
    }

    // 2. Seed Products
    const productsData = [
      {
        id: 1,
        code: 'p1',
        name: 'Apple',
        variety: '(Shimla)',
        slug: 'apple-shimla',
        category_id: 1,
        category_name: 'Fresh Fruits',
        sub_category: 'Fresh Fruits',
        unit: '1 kg',
        price: 135.00,
        old_price: 150.00,
        discount: '10% OFF',
        is_organic: true,
        is_popular: true,
        is_featured: false,
        image_url: 'prod_apple_shimla.png',
        description: 'Sweet, crisp, and freshly handpicked apples from the pristine orchards of Shimla.',
      },
      {
        id: 2,
        code: 'p2',
        name: 'Banana',
        variety: '(Robusta)',
        slug: 'banana-robusta',
        category_id: 1,
        category_name: 'Fresh Fruits',
        sub_category: 'Fresh Fruits',
        unit: '1 kg',
        price: 48.00,
        old_price: null,
        discount: null,
        is_organic: false,
        is_popular: true,
        is_featured: false,
        image_url: 'prod_banana_robusta.png',
        description: 'Naturally ripened nutrient-rich bananas packed with potassium and energy.',
      },
      {
        id: 3,
        code: 'p3',
        name: 'Tomato',
        variety: '(Local)',
        slug: 'tomato-local',
        category_id: 1,
        category_name: 'Fresh Vegetables',
        sub_category: 'Roots & Tubers',
        unit: '1 kg',
        price: 32.00,
        old_price: 36.00,
        discount: '12% OFF',
        is_organic: true,
        is_popular: true,
        is_featured: true,
        image_url: 'veg_tomato.png',
        description: 'Plump, juicy, farm-fresh red tomatoes rich in Lycopene and Vitamin C.',
      },
      {
        id: 4,
        code: 'p4',
        name: 'Potato',
        variety: '',
        slug: 'potato-fresh',
        category_id: 1,
        category_name: 'Fresh Vegetables',
        sub_category: 'Roots & Tubers',
        unit: '1 kg',
        price: 22.00,
        old_price: 25.00,
        discount: '12% OFF',
        is_organic: false,
        is_popular: true,
        is_featured: false,
        image_url: 'veg_potato.png',
        description: 'Freshly harvested soil potatoes, ideal for curries, baking, and frying.',
      },
      {
        id: 5,
        code: 'p5',
        name: 'Onion',
        variety: '',
        slug: 'onion-fresh',
        category_id: 1,
        category_name: 'Fresh Vegetables',
        sub_category: 'Roots & Tubers',
        unit: '1 kg',
        price: 28.00,
        old_price: null,
        discount: null,
        is_organic: false,
        is_popular: true,
        is_featured: false,
        image_url: 'veg_onion.png',
        description: 'Crisp, pungent red onions, an essential staple for everyday culinary cooking.',
      },
      {
        id: 6,
        code: 'p6',
        name: 'Carrot',
        variety: '',
        slug: 'carrot-fresh',
        category_id: 1,
        category_name: 'Fresh Vegetables',
        sub_category: 'Roots & Tubers',
        unit: '1 kg',
        price: 36.00,
        old_price: 40.00,
        discount: '10% OFF',
        is_organic: true,
        is_popular: true,
        is_featured: false,
        image_url: 'veg_carrot.png',
        description: 'Tender, crunchy, sweet organic carrots, packed with Beta Carotene.',
      },
      {
        id: 7,
        code: 'p7',
        name: 'Capsicum (Mix)',
        variety: '(Mix)',
        slug: 'capsicum-mix',
        category_id: 1,
        category_name: 'Fresh Vegetables',
        sub_category: 'Herbs & Seasonings',
        unit: '500 g',
        price: 45.00,
        old_price: null,
        discount: null,
        is_organic: false,
        is_popular: true,
        is_featured: false,
        image_url: 'veg_capsicum.png',
        description: 'Vibrant and crunchy bell peppers to elevate salads, stir-fries, and pasta.',
      },
      {
        id: 8,
        code: 'p8',
        name: 'Broccoli',
        variety: '',
        slug: 'broccoli-fresh',
        category_id: 1,
        category_name: 'Fresh Vegetables',
        sub_category: 'Cabbage & Cauliflower',
        unit: '250 g',
        price: 60.00,
        old_price: null,
        discount: null,
        is_organic: true,
        is_popular: true,
        is_featured: false,
        image_url: 'veg_broccoli.png',
        description: 'Crisp organic broccoli florets loaded with antioxidants and dietary fiber.',
      },
      {
        id: 9,
        code: 'v7',
        name: 'Cauliflower',
        variety: '',
        slug: 'cauliflower-fresh',
        category_id: 1,
        category_name: 'Fresh Vegetables',
        sub_category: 'Cabbage & Cauliflower',
        unit: '1 pc (approx. 500 g)',
        price: 50.00,
        old_price: null,
        discount: null,
        is_organic: false,
        is_popular: false,
        is_featured: false,
        image_url: 'veg_cauliflower.png',
        description: 'Farm-fresh compact white cauliflower heads full of wholesome nutrition.',
      },
      {
        id: 10,
        code: 'v8',
        name: 'Cucumber',
        variety: '',
        slug: 'cucumber-fresh',
        category_id: 1,
        category_name: 'Fresh Vegetables',
        sub_category: 'Gourds',
        unit: '1 kg',
        price: 28.00,
        old_price: null,
        discount: null,
        is_organic: false,
        is_popular: false,
        is_featured: false,
        image_url: 'veg_cucumber.png',
        description: 'Crisp and hydrating garden cucumbers perfect for salads and refreshments.',
      },
      {
        id: 11,
        code: 'v9',
        name: 'Brinjal',
        variety: '',
        slug: 'brinjal-fresh',
        category_id: 1,
        category_name: 'Fresh Vegetables',
        sub_category: 'Gourds',
        unit: '1 kg',
        price: 34.00,
        old_price: null,
        discount: null,
        is_organic: false,
        is_popular: false,
        is_featured: false,
        image_url: 'veg_brinjal.png',
        description: 'Glossy purple brinjals ideal for roasting, curries, and bharta.',
      },
      {
        id: 12,
        code: 'v10',
        name: 'Lady Finger',
        variety: '',
        slug: 'lady-finger-fresh',
        category_id: 1,
        category_name: 'Fresh Vegetables',
        sub_category: 'Beans & Peas',
        unit: '250 g',
        price: 32.00,
        old_price: null,
        discount: null,
        is_organic: false,
        is_popular: false,
        is_featured: false,
        image_url: 'veg_ladyfinger.png',
        description: 'Tender green bhindi hand-picked daily for maximum freshness.',
      },
      {
        id: 13,
        code: 'v11',
        name: 'Green Beans',
        variety: '',
        slug: 'green-beans-fresh',
        category_id: 1,
        category_name: 'Fresh Vegetables',
        sub_category: 'Beans & Peas',
        unit: '250 g',
        price: 40.00,
        old_price: null,
        discount: null,
        is_organic: false,
        is_popular: false,
        is_featured: false,
        image_url: 'veg_greenbeans.png',
        description: 'Crisp, slender French green beans bursting with natural garden goodness.',
      },
      {
        id: 14,
        code: 'v12',
        name: 'Spinach',
        variety: '',
        slug: 'spinach-fresh',
        category_id: 1,
        category_name: 'Fresh Vegetables',
        sub_category: 'Leafy Greens',
        unit: '250 g',
        price: 24.00,
        old_price: null,
        discount: null,
        is_organic: true,
        is_popular: false,
        is_featured: false,
        image_url: 'veg_spinach.png',
        description: 'Fresh organic palak leaves packed with iron, folate, and essential vitamins.',
      },
      {
        id: 15,
        code: 'cross_milk',
        name: 'Farm Fresh Milk',
        variety: 'Cow Milk',
        slug: 'farm-fresh-milk',
        category_id: 2,
        category_name: 'Dairy & Breakfast',
        sub_category: 'Dairy',
        unit: '1 L',
        price: 60.00,
        old_price: 65.00,
        discount: null,
        is_organic: false,
        is_popular: false,
        is_featured: false,
        image_url: 'cross_milk.png',
        description: 'Pure, pasteurized farm-fresh milk delivered chilled to your doorstep.',
      },
      {
        id: 16,
        code: 'cross_bread',
        name: 'Whole Wheat Bread',
        variety: 'Brown',
        slug: 'whole-wheat-bread',
        category_id: 2,
        category_name: 'Dairy & Breakfast',
        sub_category: 'Breakfast',
        unit: '400 g',
        price: 40.00,
        old_price: 45.00,
        discount: null,
        is_organic: false,
        is_popular: false,
        is_featured: false,
        image_url: 'cross_bread.png',
        description: 'Soft and nutritious 100% whole wheat bread baked fresh daily.',
      },
      {
        id: 17,
        code: 'cross_eggs',
        name: 'Farm Fresh Eggs',
        variety: 'Brown Eggs',
        slug: 'farm-fresh-eggs',
        category_id: 2,
        category_name: 'Dairy & Breakfast',
        sub_category: 'Breakfast',
        unit: '12 pcs',
        price: 72.00,
        old_price: 80.00,
        discount: null,
        is_organic: false,
        is_popular: false,
        is_featured: false,
        image_url: 'cross_eggs.png',
        description: 'High-protein farm-fresh brown eggs graded for superior quality.',
      },
      {
        id: 18,
        code: 'cross_oil',
        name: 'Cold Pressed Cooking Oil',
        variety: 'Mustard',
        slug: 'cold-pressed-cooking-oil',
        category_id: 4,
        category_name: 'Atta, Rice & Staples',
        sub_category: 'Oils & Ghee',
        unit: '1 L',
        price: 150.00,
        old_price: 165.00,
        discount: null,
        is_organic: false,
        is_popular: false,
        is_featured: false,
        image_url: 'cross_oil.png',
        description: 'Traditional kachi ghani cold-pressed mustard oil with authentic aroma.',
      },
      {
        id: 19,
        code: 'staple_rice',
        name: 'Premium Basmati Rice',
        variety: 'Royal',
        slug: 'premium-basmati-rice',
        category_id: 4,
        category_name: 'Atta, Rice & Staples',
        sub_category: 'Rice & Grains',
        unit: '1 kg',
        price: 110.00,
        old_price: 135.00,
        discount: '18% OFF',
        is_organic: false,
        is_popular: false,
        is_featured: false,
        image_url: 'cat_grid_staples.jpg',
        description: 'Extra long grain aged Basmati rice with delightful fragrance.',
      },
    ];

    for (const prod of productsData) {
      await Product.findOrCreate({
        where: { code: prod.code },
        defaults: prod,
      });
    }

    // 3. Seed Product Quantity Options (e.g. for Tomato / id 3)
    const tomatoProduct = await Product.findOne({ where: { code: 'p3' } });
    if (tomatoProduct) {
      const quantityOptions = [
        { product_id: tomatoProduct.id, weight_id: '250g', weight_label: '250 g', price: 10.00, old_price: 12.00, is_default: false },
        { product_id: tomatoProduct.id, weight_id: '500g', weight_label: '500 g', price: 18.00, old_price: 20.00, is_default: false },
        { product_id: tomatoProduct.id, weight_id: '1kg', weight_label: '1 kg', price: 32.00, old_price: 36.00, is_default: true },
        { product_id: tomatoProduct.id, weight_id: '2kg', weight_label: '2 kg', price: 60.00, old_price: 68.00, is_default: false },
      ];

      for (const opt of quantityOptions) {
        await ProductQuantityOption.findOrCreate({
          where: { product_id: opt.product_id, weight_id: opt.weight_id },
          defaults: opt,
        });
      }
    }

    // 4. Seed Default User
    const hashedPassword = await bcrypt.hash('password123', 10);
    const [user] = await User.findOrCreate({
      where: { phone: '+91 98765 43210' },
      defaults: {
        name: 'Aryan Mangla',
        email: 'aryan.mangla@example.com',
        phone: '+91 98765 43210',
        password: hashedPassword,
        avatar: 'user_aryan.png',
        role: 'customer',
        is_gold_member: true,
        wallet_balance: 250.00,
      },
    });

    // 5. Seed Address
    await Address.findOrCreate({
      where: { user_id: user.id, is_default: true },
      defaults: {
        user_id: user.id,
        title: 'Home',
        recipient_name: 'Aryan Mangla',
        phone: '+91 98765 43210',
        address_line: 'Sector 67, Gurugram',
        sector: 'Sector 67',
        city: 'Gurugram',
        state: 'Haryana',
        pincode: '122001',
        is_default: true,
      },
    });

    // 6. Seed Cart & Cart Items
    const [cart] = await Cart.findOrCreate({
      where: { user_id: user.id },
      defaults: { user_id: user.id },
    });

    const initialCartProducts = [
      { code: 'p3', quantity: 1, unit: '1 kg', price: 32.00 },
      { code: 'p2', quantity: 2, unit: '1 kg', price: 48.00 },
      { code: 'p4', quantity: 1, unit: '1 kg', price: 22.00 },
      { code: 'p5', quantity: 1, unit: '1 kg', price: 28.00 },
    ];

    for (const item of initialCartProducts) {
      const prod = await Product.findOne({ where: { code: item.code } });
      if (prod) {
        await CartItem.findOrCreate({
          where: { cart_id: cart.id, product_id: prod.id },
          defaults: {
            cart_id: cart.id,
            product_id: prod.id,
            quantity: item.quantity,
            unit: item.unit,
            unit_price: item.price,
          },
        });
      }
    }

    // 7. Seed Sample Order
    const existingOrder = await Order.findOne({ where: { order_number: 'ORD123456' } });
    if (!existingOrder) {
      const order = await Order.create({
        order_number: 'ORD123456',
        user_id: user.id,
        delivery_address: 'Sector 67, Gurugram 122001',
        delivery_option: 'standard',
        delivery_charge: 0.00,
        total_mrp: 159.00,
        total_discount: 23.00,
        total_amount: 136.00,
        payment_method: 'upi',
        payment_status: 'paid',
        order_status: 'Order Placed',
        estimated_delivery: 'Today by 5:00 PM',
      });

      const orderItemsData = [
        { product_id: 3, product_name: 'Tomato', unit: '1 kg', price: 32.00, old_price: 36.00, quantity: 1, total_price: 32.00, image_url: 'veg_tomato.png' },
        { product_id: 2, product_name: 'Banana', unit: '1 kg', price: 48.00, old_price: null, quantity: 2, total_price: 96.00, image_url: 'item_banana.png' },
        { product_id: 4, product_name: 'Potato', unit: '1 kg', price: 22.00, old_price: 25.00, quantity: 1, total_price: 22.00, image_url: 'veg_potato.png' },
        { product_id: 5, product_name: 'Onion', unit: '1 kg', price: 28.00, old_price: null, quantity: 1, total_price: 28.00, image_url: 'veg_onion.png' },
      ];

      for (const oi of orderItemsData) {
        await OrderItem.create({
          order_id: order.id,
          ...oi,
        });
      }
    }

    console.log('✓ Freshora database successfully seeded with categories, products, user, cart & order.');
  } catch (err) {
    console.error('✗ Failed to seed database:', err);
  }
}
